refactor(code): move dependency installers to configurator

diff --git a/config b/config
--- a/config
+++ b/config
@@ -31,6 +31,13 @@ INC_FILES=(
 	"$REPO_LIB/rm/log"
 )
 
+TOOLS=(
+	"git"
+	"yq"
+	"sponge"
+)
+
+
 [[ -f "$RM_REPO/.path" ]] && source "$RM_REPO/.path" || source "$RM_REPO/.path.dist"
 
 for i in "${!INC_FILES[@]}"
@@ -76,11 +83,96 @@ Notes:
 EOF
 }
 
+installGit() {
+	while [[ $IGIT =~ $RESP ]]
+	do
+		echo "This package requires Git"
+		echo -en "Would you like to install it now? ${DEFAULT_Y} "
+		read -n 1 -r IGIT
+		[[ -z $IGIT ]] && IGIT
+	done
+	if [[ $IGIT =~ $AFFIRM ]]; then
+		if sudo apt install -y git; then echo "Git Installed!"; else errorExit "ERROR :: Git Not Installed!"; fi
+	else
+		errorExit "Cannot proceed without git installed.  Please install Git and try again."
+	fi
+}
+
+installYq() {
+	while [[ $IYQ =~ $RESP ]]
+	do
+		echo "This package requires YQ"
+		echo -en "Would you like to install it now? ${DEFAULT_Y} "
+		read -n 1 -r IYQ
+		[[ -z $IYQ ]] && IYQ
+	done
+	if [[ $IYQ =~ $AFFIRM ]]; then
+		sudo add-apt-repository ppa:rmescandon/yq
+		sudo apt update -y
+		if sudo apt install -y yq; then echo "YQ Installed!"; else errorExit "ERROR :: YQ Not Installed!"; fi
+		yq shell-completion bash | sudo tee /etc/bash_completion.d/yq-completion.bash &> /dev/null
+		source <(yq shell-completion bash)
+	else
+		errorExit "Cannot proceed without yq installed.  Please install YQ and try again."
+	fi
+}
+
+installUtils() {
+	while [[ $IGIT =~ $RESP ]]
+	do
+		echo "This package requires MoreUtils"
+		echo -en "Would you like to install it now? ${DEFAULT_Y} "
+		read -n 1 -r IUTIL
+		[[ -z $IUTIL ]] && IUTIL
+	done
+	if [[ $IUTIL =~ $AFFIRM ]]; then
+		if sudo apt install -y git; then echo "Git Installed!"; else errorExit "ERROR :: Git Not Installed!"; fi
+	else
+		errorExit "Cannot proceed without git installed.  Please install Git and try again."
+	fi
+}
+
+installTool() {
+	case "$1" in
+		git)
+			installGit;;
+		yq)
+			installYq;;
+		sponge)
+			installUtils;;
+		*)
+			errorExit "release :: Invalid Argument"
+	esac
+}
+
+# overridden function
+checkCMD() {
+	local fail=true
+	local inst=false
+	[[ -n "$2" && "$2" == 'nofail' ]] && fail=false
+	[[ -n "$3" && "$3" == 'install' ]] && inst=true
+    if ! command -v "$1" &>/dev/null; then
+        echo "ERROR: Command '$1' Not Found!"
+        [[ "$fail" == true ]] && exit 1
+        [[ "$inst" == true ]] && installTool "$1"
+    fi
+}
+
+check() {
+	if [[ "${#TOOLS[@}" -gt 0 ]]; then
+		for i in "${!TOOLS[@]}"; do
+			checkCMD "${TOOLS[$i]}"
+		done
+	fi
+}
+
 setup() {
 	clear
     echo "Release Manager Configurator"
     echo
     echo "Configuring Global Environment Variables"
+
+    check
 
     [[ ! -f "$RM_REPO/.path" ]] && install -m 644 -g "$user" -o "$user" "$RM_REPO/.path.dist" "$RM_REPO/.path"
 
diff --git a/src/etc/release b/src/etc/release
--- a/src/etc/release
+++ b/src/etc/release
@@ -13,7 +13,11 @@
 # ==================================================================
 # Release Manager Executable
 # ==================================================================
+exec 2>>"$RM_LOG/error"
+
 set -e
+
+trap 'errorHandler $? ${LINENO}' ERR
 #-------------------------------------------------------------------
 # DEPENDENCIES
 #-------------------------------------------------------------------
@@ -25,23 +29,170 @@ declare -Agx PROFILE
 
 PROFILE["STARTTIME"]="$(date +%s.%N)"
 
+declare -agx FILES
+declare -agx TOOLS
+
+declare -gx LOGGING
+
 declare -gx WORKING_BRANCH
 declare -gx STAGING_BRANCH
 declare -gx PRODUCT_BRANCH
+
+declare -gx tempdir
+
+tempdir="$(mktemp -d)"
+
+declare -gx CFGDIR="$RM_OPT/cfg"
+declare -gx TMPLDIR="$RM_OPT/inc/tpl"
+
+declare -gx sfx
+declare -gx _version
+
+declare -gx TYPE
+declare -gx TAG
 
 #-------------------------------------------------------------------
 # FUNCTIONS
 #-------------------------------------------------------------------
 
 help() {
-	echo
+	cat << EOF
+
+Project Executable - The core functionality of Release Manager
+
+Usage:
+
+	release <options>
+
+	eg:	release -t version v1.0.0
+
+Options:
+
+	-h, --help				Display this help information
+	-u, --update			Update Release Manager
+	-n, --uninstall			Uninstall Release Manager
+	-t, --type				Process Release Type: (requires additional argument)
+	-l, --log				Set Logging to (requires additional argument)
+								- false
+								- true
+									- if true will accept an additional optional argument being the logfile path
+										eg: release -t minor -l /var/log/myLog
+
+	Valid "Types":
+
+		preview				Preview Release
+		prerelease			Prerelease (receives optional tertiary argument (eg: release -t prerelease alpha)
+		first				First Release (system will not increment configured version number)
+		patch				Patch Release (system increments third digit)
+		minor				Minor Release (system increments second digit, third digit 0)
+		major				Major Release (system increments first digit, second & third digits 0)
+		version				Specified Version Release (version argument required - eg: release -t version 1.3.2)
+
+	Notes:
+
+	If you DO NOT specify a type, the system will do its best to determine the most appropriate version number
+	according to your git commit logs - HOWEVER - it's not particularly smart just yet ... you may encounter glitches
+
+	You must run this software using a ROOT ACCOUNT ONLY
+
+EOF
+}
+
+errorHandler() {
+    local errNo="${1}"
+    local lineNo="${2}"
+
+    if [[ -f "$RM_LOG/error" ]]; then
+        errMsg=$(tail -1 "$RM_LOG/error")
+    else
+        errMsg="Unknown Error"
+    fi
+    if [[ $LOGGING == true ]]; then
+        echoLog "ERROR: ($errNo) $errMsg on Line $lineNo"
+    else
+        echo "ERROR: ($errNo) $errMsg on Line $lineNo"
+    fi
+    exit 1
+}
+
+getConfig() {
+	if [[ $LOGGING == true ]]; then
+		echoLog "Configuring Release Manager" --color=gold
+		echoLog "separator"
+	fi
+
+    cfgFile="$(find "$PWD" -maxdepth 1 -type f -regextype posix-egrep -iregex ".+\.(release|releaserc|versionrc)(\.json)?")"
+    cfgDef="$(find "$CFGDIR" -maxdepth 1 -type f -regextype posix-egrep -iregex ".+\..*\.(rel|std)(\.json)?")"
+
+    if [[ -n "$cfgFile" ]]; then
+    	[[ $LOGGING == true ]] && echoLog "Discovered Config File: '$cfgFile'"
+    	readConfig "$cfgFile"
+    elif [[ -f "$cfgDef" ]]; then
+    	[[ $LOGGING == true ]] && echoLog "Using Config File: '$cfgDef'"
+    	readConfig "$cfgDef"
+    else
+    	[[ $LOGGING == true ]] && echoLog "Writing Config File: '$RM_OPT/.releaserc'"
+    	defaultConfig
+    	readConfig "$RM_OPT/.releaserc"
+    fi
+
+    if [[ -z "$(git config --get user.email)" ]]; then
+		echo
+    fi
+}
+
+readConfig() {
+	[[ ! -f "$1" ]] && defaultConfig
+}
+
+defaultConfig() {
+	cat << EOF > "$RM_OPT/.releaserc"
+{
+    "id": "default",
+    "prettyName": "Default",
+    "version": "0.1.0",
+    "extends": "angular",
+    "git": {
+        "user": {
+            "name": "Ragdata",
+            "email": "ragdata@users.noreply.github.com"
+        },
+        "branches": {
+            "prod": "master",
+            "patch": "dev/.*"
+        }
+    },
+    "files": [
+        ".releaserc",
+        "README.md",
+        "COPYRIGHT"
+    ]
+}
+EOF
+}
+
+check() {
+	if [[ "${#FILES[@]}" -gt 0 ]]; then
+		for i in "${!FILES[@]}"; do
+			checkSrc "${FILES[$i]}"
+		done
+	fi
+}
+
+main() {
+	[[ $LOGGING == true ]] && clear
+
+	check
+
+	getConfig
+
 }
 
 #-------------------------------------------------------------------
 # MAIN
 #-------------------------------------------------------------------
 
-OPTIONS=$(getopt -l "update,uninstall,type:,help" -o "unt:h" -a -- "$@")
+OPTIONS=$(getopt -l "update,uninstall,type:,log::,help" -o "unt:l::h" -a -- "$@")
 
 eval set --"$OPTIONS"
 
@@ -51,15 +202,64 @@ do
 		-u|--update)
 			source "$RM_LIB/rm-install"
 			rmUpdate
+			shift
 			;;
 		-n|--uninstall)
 			source "$RM_LIB/rm-install"
 			rmUninstall
+			shift
 			;;
 		-t|--type)
 			case $2 in
-
+				preview)
+					TYPE="preview"
+					shift 2
+					;;
+				prerelease)
+					TYPE="prerelease"
+					[[ -n "$3" ]] && sfx="${3:-}"
+					shift 3
+					;;
+				first)
+					TYPE="first"
+					shift 2
+					;;
+				patch)
+					TYPE="patch"
+					shift 2
+					;;
+				minor)
+					TYPE="minor"
+					shift 2
+					;;
+				major)
+					TYPE="major"
+					shift 2
+					;;
+				version)
+					TYPE="version"
+					_version="${3:-}"
+					shift 3
+					;;
+				--)
+					help
+					exit 1
+					;;
+				*)
+					errorExit "release :: Invalid Argument"
+					;;
 			esac
+			;;
+		-l|--log)
+			state="${2:-}"
+			if [[ -z "$state" ]]; then
+				state=true
+				shift
+			else
+				state="$2"
+				shift 2
+			fi
+			LOGGING="$state"
 			;;
 		-h|--help)
 			help
@@ -73,5 +273,11 @@ do
 			errorExit "release :: Invalid Argument"
 			;;
 	esac
-	shift
 done
+
+[[ -z "$TYPE" ]] && TYPE="auto"
+
+main
+
+# reset all traps
+trap - 0 ERR
diff --git a/src/lib/rm/functions b/src/lib/rm/functions
--- a/src/lib/rm/functions
+++ b/src/lib/rm/functions
@@ -220,21 +220,29 @@ checkFile() {
     fi
 }
 #
-# checkSrc
+# checkSrc - checks if a particular file is accessible
+#		   - accepts an additional argument:
+#			   - "nofail" - function will not exit on failure
 #
 checkSrc() {
+	local fail=true
+	[[ -n "$2" && "$2" == 'nofail' ]] && fail=false
     if [[ ! -f "$1" && ! -d "$1" ]]; then
         echo "ERROR: Missing File '$1'!"
-        exit 1
+        [[ "$fail" == true ]] && exit 1
     fi
 }
 #
-# checkCmd
+# checkCmd - checks if a particular command can be executed
+#		   - accepts an additional argument:
+#			   - "nofail" - function will not exit on failure
 #
 checkCmd() {
+	local fail=true
+	[[ -n "$2" && "$2" == 'nofail' ]] && fail=false
     if ! command -v "$1" &>/dev/null; then
         echo "ERROR: Command '$1' Not Found!"
-        exit 1
+        [[ "$fail" == true ]] && exit 1
     fi
 }
 #
@@ -380,9 +388,9 @@ checkRoot()
     [[ "$EUID" -ne 0 ]] && errorExit "This script MUST be run as root!"
 }
 #
-# checkCMD - checks that the system has access to each of the commands listed in an array named TOOLS
+# checkCMDs - checks that the system has access to each of the commands listed in an array named TOOLS
 #
-checkCMD()
+checkCMDs()
 {
     for i in "${!TOOLS[@]}"; do
         if ! command -v "${TOOLS[$i]}" &> /dev/null; then
@@ -410,4 +418,10 @@ getPassword()
     done
 
     echoLog "$passwd"
+}
+#
+# mkd
+#
+mkd() {
+    mkdir -p "$@" && cd "$@" || return 1
 }
